Disable avx512 build

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -18,14 +18,14 @@ jobs:
       REGISTRY: us-east1-docker.pkg.dev/entrelia-prod/entrelia
 
     steps:
-    - name: Machine Info
-      run: |
-        lscpu
-        lscpu | grep -i AVX512
-    - if: failure()
-      run: |
-        echo "Runner CPU does not support AVX512"
-        exit 1
+#    - name: Machine Info
+#      run: |
+#        lscpu
+#        lscpu | grep -i AVX512
+#    - if: failure()
+#      run: |
+#        echo "Runner CPU does not support AVX512"
+#        exit 1
     - uses: actions/checkout@v3
     - uses: google-github-actions/auth@v2
       with:
@@ -37,7 +37,7 @@ jobs:
       run: gcloud auth configure-docker us-east1-docker.pkg.dev
     - name: Build Docker Container
       run: |
-        docker build -f Dockerfile.cpu -t ${{ env.REGISTRY }}/vllm-cpu:${{ github.sha }} --shm-size=4g .
+        docker build --build-arg VLLM_CPU_DISABLE_AVX512="true" -f Dockerfile.cpu -t ${{ env.REGISTRY }}/vllm-cpu:${{ github.sha }} --shm-size=4g .
     - name: Push Docker Container
       run: |
         docker push ${{ env.REGISTRY }}/vllm-cpu:${{ github.sha }}
